file_format: "1"
id: quefrency_60
name: Quefrency 60% Rev. 1
type: shield
url: https://github.com/keebio/quefrency-rev1-pcb
requires: [pro_micro]
features:
  - keys
  - encoder
siblings:
  - quenfrency_60_left
  - quenfrency_60_right
